name: Docker Image CI

on:
  push:
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the Docker image
        run: docker buildx build --push --platform linux/amd64,linux/arm64 --tag djirik/gokafka:$BRANCH_NAME .
